// QMK/ZMK Keycode to Fluent UI Icon mapping table
export const ICON_ALIASES = {
  // Power & System Controls
  KC_SYSTEM_POWER: 'KC_KB_POWER',
  KC_PWR: 'KC_KB_POWER',
  KC_SLEP: 'KC_SYSTEM_SLEEP',
  KC_WAKE: 'KC_SYSTEM_WAKE',

  // Audio / Sound Controls
  KC_MUTE: 'KC_AUDIO_MUTE',
  KC_KB_VOLUME_UP: 'KC_AUDIO_VOL_UP',
  KC_VOLU: 'KC_AUDIO_VOL_UP',
  KC_KB_VOLUME_DOWN: 'KC_AUDIO_VOL_DOWN',
  KC_VOLD: 'KC_AUDIO_VOL_DOWN',

  // Media Controls
  KC_MEDIA_PLAY: 'KC_MEDIA_PLAY_PAUSE',
  KC_MPLY: 'KC_MEDIA_PLAY_PAUSE',
  KC_MSTP: 'KC_MEDIA_STOP',
  KC_MNXT: 'KC_MEDIA_NEXT_TRACK',
  KC_MPRV: 'KC_MEDIA_PREV_TRACK',
  KC_MFFD: 'KC_MEDIA_FAST_FORWARD',
  KC_MRWD: 'KC_MEDIA_REWIND',
  KC_EJCT: 'KC_MEDIA_EJECT',
  KC_MSEL: 'KC_MEDIA_SELECT',

  // Brightness Controls
  KC_BRIGHTNESS_UP: 'KC_KB_BRIGHTNESS_UP',
  KC_BRIU: 'KC_KB_BRIGHTNESS_UP',
  KC_BRIGHTNESS_DOWN: 'KC_KB_BRIGHTNESS_DOWN',
  KC_BRID: 'KC_KB_BRIGHTNESS_DOWN',

  // WWW & Browser Operations
  KC_MYCM: 'KC_MY_COMPUTER',
  KC_WHOM: 'KC_WWW_HOME',
  KC_WBAK: 'KC_WWW_BACK',
  KC_WWW_BACK_ALT: 'KC_WWW_BACK',
  KC_WFWD: 'KC_WWW_FORWARD',
  KC_WWW_FORWARD_ALT: 'KC_WWW_FORWARD',
  KC_WSTP: 'KC_WWW_STOP',
  KC_WREF: 'KC_WWW_REFRESH',
  KC_WFAV: 'KC_WWW_FAVORITES',

  // Utility Controls
  KC_CPNL: 'KC_CONTROL_PANEL',
  KC_ASST: 'KC_ASSISTANT',
  KC_MCTL: 'KC_MISSION_CONTROL',
  KC_LPAD: 'KC_LAUNCHPAD',

  // Standard Keyboard Key Aliases
  KC_PENT: 'KC_ENT',
  KC_REDO: 'KC_AGAIN',
  KC_LSHIFT: 'KC_LSFT',
  KC_RSHIFT: 'KC_RSFT',
  LSHIFT: 'KC_LSFT',
  RSHIFT: 'KC_RSFT',
  LSFT: 'KC_LSFT',
  RSFT: 'KC_RSFT',

  // QMK Magic Controls (Mapped cleanly to arrow swap or keyboard icons)
  KC_MAGIC_TOGGLE_CONTROL_CAPS_LOCK: 'ic_fluent_arrow_swap_24_regular',
  MAGIC_TOGGLE_CONTROL_CAPS_LOCK: 'ic_fluent_arrow_swap_24_regular',
  KC_MAGIC_TOGGLE_ESCAPE_CAPS_LOCK: 'ic_fluent_arrow_swap_24_regular',
  MAGIC_TOGGLE_ESCAPE_CAPS_LOCK: 'ic_fluent_arrow_swap_24_regular',
  KC_MAGIC_TOGGLE_CTL_GUI: 'ic_fluent_arrow_swap_24_regular',
  MAGIC_TOGGLE_CTL_GUI: 'ic_fluent_arrow_swap_24_regular',
  KC_MAGIC_TOGGLE_ALT_GUI: 'ic_fluent_arrow_swap_24_regular',
  MAGIC_TOGGLE_ALT_GUI: 'ic_fluent_arrow_swap_24_regular',
  KC_MAGIC_TOGGLE_BACKSLASH_BACKSPACE: 'ic_fluent_arrow_swap_24_regular',
  MAGIC_TOGGLE_BACKSLASH_BACKSPACE: 'ic_fluent_arrow_swap_24_regular',
  KC_MAGIC_TOGGLE_GRAVE_ESC: 'ic_fluent_arrow_swap_24_regular',
  MAGIC_TOGGLE_GRAVE_ESC: 'ic_fluent_arrow_swap_24_regular',
  KC_CG_TOGG: 'ic_fluent_arrow_swap_24_regular',
  CG_TOGG: 'ic_fluent_arrow_swap_24_regular',
  KC_AG_TOGG: 'ic_fluent_arrow_swap_24_regular',
  AG_TOGG: 'ic_fluent_arrow_swap_24_regular',

  KC_MAGIC_TOGGLE_NKRO: 'ic_fluent_keyboard_24_regular',
  MAGIC_TOGGLE_NKRO: 'ic_fluent_keyboard_24_regular',

  KC_MAGIC_TOGGLE_GUI: 'ic_fluent_lock_closed_24_regular',
  MAGIC_TOGGLE_GUI: 'ic_fluent_lock_closed_24_regular',

  // Wireless Connection Keycodes Specific Mappings
  KC_OUT_AUTO: 'ic_fluent_bluetooth_connected_24_regular',
  KC_OUT_USB: 'ic_fluent_connector_24_regular',
  KC_OUT_BT: 'ic_fluent_bluetooth_24_regular',
  KC_OUT_2G4: 'ic_fluent_wifi_1_24_regular',

  KC_BT_SEL_0: 'ic_fluent_bluetooth_24_regular',
  KC_BT_SEL_1: 'ic_fluent_bluetooth_24_regular',
  KC_BT_SEL_2: 'ic_fluent_bluetooth_24_regular',
  KC_BT_SEL_3: 'ic_fluent_bluetooth_24_regular',
  KC_BT_SEL_4: 'ic_fluent_bluetooth_24_regular',
  KC_BT_NXT: 'ic_fluent_bluetooth_24_regular',
  KC_BT_PRV: 'ic_fluent_bluetooth_24_regular',
  KC_BT_ON: 'ic_fluent_bluetooth_24_regular',

  KC_BT_CLR: 'ic_fluent_bluetooth_disabled_24_regular',
  KC_BT_CLR_ALL: 'ic_fluent_bluetooth_disabled_24_regular',
  KC_BT_OFF: 'ic_fluent_bluetooth_disabled_24_regular',

  KC_BT_TOGG: 'ic_fluent_bluetooth_searching_24_regular',

  // QMK Short Keycodes & Helper Mappings
  KC_FIND: 'KC_WWW_SEARCH',
  KC_KB_MUTE: 'KC_AUDIO_MUTE',
  KC_DEBUG: 'DEBUG',
  KC_RESET: 'KC_RESET',
  KC_QK_BOOT: 'KC_QK_BOOT',
  KC_EE_CLR: 'KC_EE_CLR',
  KC_AST_TOG: 'KC_CAPS',
  KC_WSCH: 'KC_WWW_SEARCH',

  // ZMK Style Short Connection Keycodes
  OUT_AUTO: 'KC_OUT_AUTO',
  OUT_USB: 'KC_OUT_USB',
  OUT_BT: 'KC_OUT_BT',
  OUT_2G4: 'KC_OUT_2G4',
  OUT_TOG: 'KC_BT_TOGG',
  OUT_BLE: 'KC_OUT_BT',
  BT_SEL_0: 'KC_BT_SEL_0',
  BT_SEL_1: 'KC_BT_SEL_1',
  BT_SEL_2: 'KC_BT_SEL_2',
  BT_SEL_3: 'KC_BT_SEL_3',
  BT_SEL_4: 'KC_BT_SEL_4',
  BT_SEL0: 'KC_BT_SEL_0',
  BT_SEL1: 'KC_BT_SEL_1',
  BT_SEL2: 'KC_BT_SEL_2',
  BT_SEL3: 'KC_BT_SEL_3',
  BT_SEL4: 'KC_BT_SEL_4',
  BT_CLR: 'KC_BT_CLR',
  BT_CLR_ALL: 'KC_BT_CLR_ALL',
  BT_TOGG: 'KC_BT_TOGG',
  BT_NXT: 'KC_BT_NXT',
  BT_PRV: 'KC_BT_PRV',
  BT_ON: 'KC_BT_ON',
  BT_OFF: 'KC_BT_OFF',

  // ZMK Style Short Mouse Keycodes
  MS_U: 'KC_MS_U',
  MS_D: 'KC_MS_D',
  MS_L: 'KC_MS_L',
  MS_R: 'KC_MS_R',
  MS_UP: 'KC_MS_U',
  MS_DN: 'KC_MS_D',
  MS_LT: 'KC_MS_L',
  MS_RT: 'KC_MS_R',
  MOVE_UP: 'KC_MS_U',
  MOVE_DOWN: 'KC_MS_D',
  MOVE_LEFT: 'KC_MS_L',
  MOVE_RIGHT: 'KC_MS_R',
  BTN1: 'KC_BTN1',
  BTN2: 'KC_BTN2',
  BTN3: 'KC_BTN3',
  BTN4: 'KC_BTN4',
  BTN5: 'KC_BTN5',
  WH_U: 'KC_WH_U',
  WH_D: 'KC_WH_D',
  WH_L: 'KC_WH_L',
  WH_R: 'KC_WH_R',
  WHL_UP: 'KC_WH_U',
  WHL_DN: 'KC_WH_D',
  WHL_LT: 'KC_WH_L',
  WHL_RT: 'KC_WH_R',
  SCROLL_UP: 'KC_WH_U',
  SCROLL_DOWN: 'KC_WH_D',
  SCROLL_LEFT: 'KC_WH_L',
  SCROLL_RIGHT: 'KC_WH_R',
  ACL0: 'KC_ACL0',
  ACL1: 'KC_ACL1',
  ACL2: 'KC_ACL2',
};
