window.DEFAULT_LAYOUT_DATA = {
  "name": "ZUOYA GMK70",
  "vendorId": "0x342d",
  "productId": "0xe491",
  "keycodes": ["qmk_lighting"],
  "menus": [
    {
      "label": "Lighting",
      "content": [
        {
          "label": "Backlight",
          "content": [
            {
              "label": "Brightness",
              "type": "range",
              "options": [0, 255],
              "content": ["id_qmk_rgb_matrix_brightness", 3, 1]
            },
            {
              "label": "Effect",
              "type": "dropdown",
              "content": ["id_qmk_rgb_matrix_effect", 3, 2],
              "options": [
                ["All Off", 0],
                ["Solid Color", 1],
                ["Alphas Mods", 2],
                ["Gradient Up Down", 3],
                ["Gradient Left Right", 4],
                ["Breathing", 5],
                ["Band Sat", 6],
                ["Band Val", 7],
                ["Band Pinwheel Sat", 8],
                ["Band Pinwheel Val", 9],
                ["Band Spiral Sat", 10],
                ["Band Spiral Val", 11],
                ["Cycle All", 12],
                ["Cycle Left Right", 13],
                ["Cycle Up Down", 14],
                ["Rainbow Moving Chevron", 15],
                ["Cycle Out In", 16],
                ["Cycle Out In Dual", 17],
                ["Cycle Pinwheel", 18],
                ["Cycle Spiral", 19],
                ["Dual Beacon", 20],
                ["Rainbow Beacon", 21],
                ["Rainbow Pinwheels", 22],
                ["Raindrops", 23],
                ["Jellybean Raindrops", 24],
                ["Hue Breathing", 25],
                ["Hue Pendulum", 26],
                ["Hue Wave", 27],
                ["Pixel Rain", 28],
                ["Pixel Flow", 29],
                ["Pixel Fractal", 30],
                ["Typing Heatmap", 31],
                ["Digital Rain", 32],
                ["Solid Reactive Simple", 33],
                ["Solid Reactive", 34],
                ["Solid Reactive Wide", 35],
                ["Solid Reactive Multiwide", 36],
                ["Solid Reactive Cross", 37],
                ["Solid Reactive Multicross", 38],
                ["Solid Reactive Nexus", 39],
                ["Solid Reactive Multinexus", 40],
                ["Splash", 41],
                ["Multisplash", 42],
                ["Solid Splash", 43],
                ["Solid Multisplash", 44],
                ["Close All", 45]
              ]
            },
            {
              "showIf": "{id_qmk_rgb_matrix_effect} != 0",
              "label": "Effect Speed",
              "type": "range",
              "options": [0, 255],
              "content": ["id_qmk_rgb_matrix_effect_speed", 3, 3]
            },
            {
              "showIf": "{id_qmk_rgb_matrix_effect} != 0 && {id_qmk_rgb_matrix_effect} != 24 && {id_qmk_rgb_matrix_effect} != 28 && {id_qmk_rgb_matrix_effect} != 29 && {id_qmk_rgb_matrix_effect} != 32",
              "label": "Color",
              "type": "color",
              "content": ["id_qmk_rgb_matrix_color", 3, 4]
            }
          ]
        }
      ]
    }
  ],
  "matrix": {"rows": 10, "cols": 9},
  "customKeycodes": [
    {"name": "BT DEV1","title": "BT Device 1","shortName": "DEV1"},
    {"name": "BT DEV2","title": "BT Device 2","shortName": "DEV2"},
    {"name": "BT DEV3","title": "BT Device 3","shortName": "DEV3"},
    {"name": "BT DEV4","title": "BT Device 4","shortName": "DEV4"},
    {"name": "BT DEV5","title": "BT Device 5","shortName": "DEV5"},
    {"name": "2.4G","title": "2.4G","shortName": "DEV 2.4G"},
    {"name": "USB","title": "USB","shortName": "DEV USB"}
  ],
  "layouts": {
      "keymap":
        [
          [
            {
              "c": "#777777"
            },
            "0,0\n\n\n\n\n\n\n\n\ne0",
            {
              "x": 0.25,
              "c": "#cccccc"
            },
            "0,1",
            "0,2",
            "0,3",
            "0,4",
            "0,5",
            "0,6",
            "0,7",
            {
              "x": 0.5
            },
            "5,1",
            "5,2",
            "5,3",
            "5,4",
            "5,5",
            "5,6",
            "5,7",
            {
              "c": "#aaaaaa",
              "w": 2
            },
            "5,8"
          ],
          [
            {
              "c": "#cccccc"
            },
            "1,0",
            {
              "x": 0.25,
              "c": "#aaaaaa",
              "w": 1.5
            },
            "1,1",
            {
              "c": "#cccccc"
            },
            "1,2",
            "1,3",
            "1,4",
            "1,5",
            "1,6",
            {
              "x": 1.5
            },
            "6,1",
            "6,2",
            "6,3",
            "6,4",
            "6,5",
            "6,6",
            "6,7",
            {
              "w": 1.5
            },
            "6,8"
          ],
          [
            "2,0",
            {
              "x": 0.25,
              "c": "#aaaaaa",
              "w": 1.75
            },
            "2,1",
            {
              "c": "#cccccc"
            },
            "2,2",
            "2,3",
            "2,4",
            "2,5",
            "2,6",
            {
              "x": 1.5
            },
            "7,1",
            "7,2",
            "7,3",
            "7,4",
            "7,5",
            {
              "c": "#777777"
            },
            "7,6",
            {
              "c": "#cccccc",
              "w": 2.25
            },
            "7,7"
          ],
          [
            "3,0",
            {
              "x": 0.25,
              "c": "#aaaaaa",
              "w": 2.25
            },
            "3,1",
            {
              "c": "#cccccc"
            },
            "3,2",
            "3,3",
            "3,4",
            "3,5",
            "3,6",
            {
              "x": 0.25
            },
            "8,0",
            "8,1",
            "8,2",
            "8,3",
            "8,4",
            {
              "c": "#aaaaaa"
            },
            "8,5",
            {
              "c": "#cccccc"
            },
            "8,6",
            "8,7",
            "8,8"
          ],
          [
            {
              "c": "#aaaaaa"
            },
            "4,0",
            {
              "x": 0.25,
              "w": 1.25
            },
            "4,1",
            {
              "w": 1.25
            },
            "4,2",
            {
              "w": 1.25
            },
            "4,3",
            {
              "x": 0.25,
              "w": 3
            },
            "4,5",
            {
              "x": 0.75,
              "c": "#cccccc",
              "w": 2.75
            },
            "9,1",
            {
              "c": "#aaaaaa",
              "w": 1.25
            },
            "9,3",
            {
              "w": 1.25
            },
            "9,4",
            {
              "x": 0.5
            },
            "9,6",
            "9,7",
            {
              "c": "#cccccc"
            },
            "9,8"
          ]
        ]
  }
}
;
window.DEFAULT_MAPPING_DATA = {
  "name": "ZUOYA GMK70",
  "vendorProductId": 875422865,
  "macros": [
    "{+KC_LGUI}{+KC_LCTL}v{-KC_LCTL}{-KC_LGUI}",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ""
  ],
  "layers": [
    [
      "KC_MUTE",
      "A(KC_GRV)",
      "KC_1",
      "KC_2",
      "KC_3",
      "KC_4",
      "KC_5",
      "KC_6",
      "KC_NO",
      "KC_ESC",
      "KC_TAB",
      "KC_Q",
      "KC_W",
      "KC_E",
      "KC_R",
      "KC_T",
      "KC_NO",
      "KC_NO",
      "KC_HOME",
      "KC_GRV",
      "KC_A",
      "KC_S",
      "KC_D",
      "KC_F",
      "KC_G",
      "KC_NO",
      "KC_NO",
      "KC_END",
      "KC_LSFT",
      "KC_Z",
      "KC_X",
      "KC_C",
      "KC_V",
      "KC_B",
      "KC_NO",
      "KC_NO",
      "MACRO(0)",
      "KC_LCTL",
      "KC_LGUI",
      "KC_LALT",
      "KC_NO",
      "KC_SPC",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_PSCR",
      "KC_7",
      "KC_8",
      "KC_9",
      "KC_0",
      "KC_MINS",
      "KC_EQL",
      "KC_BSPC",
      "KC_NO",
      "KC_Y",
      "KC_U",
      "KC_I",
      "KC_O",
      "KC_P",
      "KC_LBRC",
      "KC_RBRC",
      "KC_DEL",
      "KC_NO",
      "KC_H",
      "KC_J",
      "KC_K",
      "KC_L",
      "KC_SCLN",
      "KC_QUOT",
      "KC_ENT",
      "KC_NO",
      "KC_BSLS",
      "KC_N",
      "KC_M",
      "KC_COMM",
      "KC_DOT",
      "KC_SLSH",
      "KC_RSFT",
      "KC_UP",
      "KC_RCTL",
      "KC_NO",
      "KC_F7",
      "KC_NO",
      "KC_RALT",
      "MO(1)",
      "KC_NO",
      "KC_LEFT",
      "KC_DOWN",
      "KC_RGHT"
    ],
    [
      "KC_TRNS",
      "KC_TRNS",
      "KC_F1",
      "KC_F2",
      "KC_F3",
      "KC_F4",
      "KC_F5",
      "KC_F6",
      "KC_NO",
      "KC_TRNS",
      "RGB_MOD",
      "CUSTOM(0)",
      "CUSTOM(1)",
      "CUSTOM(2)",
      "CUSTOM(5)",
      "KC_TRNS",
      "KC_NO",
      "KC_NO",
      "KC_TRNS",
      "KC_TRNS",
      "KC_NO",
      "TO(2)",
      "KC_TRNS",
      "KC_TRNS",
      "KC_TRNS",
      "KC_NO",
      "KC_NO",
      "KC_TRNS",
      "KC_TRNS",
      "KC_TRNS",
      "RGB_TOG",
      "KC_TRNS",
      "MAGIC_TOGGLE_NKRO",
      "CUSTOM(27)",
      "KC_NO",
      "KC_NO",
      "KC_TRNS",
      "CUSTOM(26)",
      "KC_TRNS",
      "KC_LALT",
      "KC_NO",
      "CUSTOM(7)",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_TRNS",
      "KC_F7",
      "KC_F8",
      "KC_F9",
      "KC_F10",
      "KC_F11",
      "KC_F12",
      "QK_CLEAR_EEPROM",
      "KC_NO",
      "KC_PSCR",
      "KC_SLCK",
      "KC_PAUS",
      "KC_TRNS",
      "KC_TRNS",
      "RGB_HUD",
      "RGB_HUI",
      "CUSTOM(9)",
      "KC_NO",
      "KC_HOME",
      "KC_END",
      "KC_PGUP",
      "KC_PGDN",
      "RGB_SAD",
      "RGB_SAI",
      "KC_END",
      "KC_NO",
      "CUSTOM(27)",
      "KC_TRNS",
      "KC_TRNS",
      "KC_TRNS",
      "KC_TRNS",
      "KC_TRNS",
      "CUSTOM(25)",
      "RGB_VAI",
      "KC_INS",
      "KC_NO",
      "CUSTOM(7)",
      "KC_NO",
      "KC_RALT",
      "0x700b",
      "KC_NO",
      "RGB_SPD",
      "RGB_VAD",
      "RGB_SPI"
    ],
    [
      "KC_MUTE",
      "KC_ESC",
      "KC_GRV",
      "KC_1",
      "KC_2",
      "KC_3",
      "KC_4",
      "KC_5",
      "KC_NO",
      "CUSTOM(28)",
      "KC_TAB",
      "KC_Q",
      "KC_W",
      "KC_E",
      "KC_R",
      "KC_T",
      "KC_NO",
      "KC_NO",
      "CUSTOM(29)",
      "KC_CAPS",
      "KC_A",
      "KC_S",
      "KC_D",
      "KC_F",
      "KC_G",
      "KC_NO",
      "KC_NO",
      "CUSTOM(30)",
      "KC_LSFT",
      "KC_Z",
      "KC_X",
      "KC_C",
      "KC_V",
      "KC_B",
      "KC_NO",
      "KC_NO",
      "CUSTOM(31)",
      "KC_LCTL",
      "MO(3)",
      "KC_LGUI",
      "KC_NO",
      "KC_SPC",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_6",
      "KC_7",
      "KC_8",
      "KC_9",
      "KC_0",
      "KC_MINS",
      "KC_EQL",
      "KC_BSPC",
      "KC_NO",
      "KC_Y",
      "KC_U",
      "KC_I",
      "KC_O",
      "KC_P",
      "KC_LBRC",
      "KC_RBRC",
      "KC_BSLS",
      "KC_NO",
      "KC_H",
      "KC_J",
      "KC_K",
      "KC_L",
      "KC_SCLN",
      "KC_QUOT",
      "KC_ENT",
      "KC_NO",
      "KC_B",
      "KC_N",
      "KC_M",
      "KC_COMM",
      "KC_DOT",
      "KC_SLSH",
      "KC_RSFT",
      "KC_UP",
      "KC_DEL",
      "KC_NO",
      "KC_SPC",
      "KC_NO",
      "KC_RGUI",
      "KC_RALT",
      "KC_NO",
      "KC_LEFT",
      "KC_DOWN",
      "KC_RGHT"
    ],
    [
      "KC_TRNS",
      "KC_TRNS",
      "KC_TRNS",
      "KC_F1",
      "KC_F2",
      "KC_F3",
      "KC_F4",
      "KC_F5",
      "KC_NO",
      "KC_TRNS",
      "RGB_MOD",
      "CUSTOM(0)",
      "CUSTOM(1)",
      "CUSTOM(2)",
      "CUSTOM(5)",
      "KC_TRNS",
      "KC_NO",
      "KC_NO",
      "KC_TRNS",
      "KC_TRNS",
      "TO(0)",
      "KC_NO",
      "KC_TRNS",
      "KC_TRNS",
      "KC_TRNS",
      "KC_NO",
      "KC_NO",
      "KC_TRNS",
      "KC_TRNS",
      "KC_TRNS",
      "RGB_TOG",
      "KC_TRNS",
      "KC_TRNS",
      "CUSTOM(27)",
      "KC_NO",
      "KC_NO",
      "KC_TRNS",
      "CUSTOM(26)",
      "KC_TRNS",
      "KC_LGUI",
      "KC_NO",
      "CUSTOM(7)",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_F6",
      "KC_F7",
      "KC_F8",
      "KC_F9",
      "KC_F10",
      "KC_F11",
      "KC_F12",
      "QK_CLEAR_EEPROM",
      "KC_NO",
      "KC_PSCR",
      "KC_SLCK",
      "KC_PAUS",
      "KC_TRNS",
      "KC_TRNS",
      "RGB_HUD",
      "RGB_HUI",
      "CUSTOM(9)",
      "KC_NO",
      "KC_HOME",
      "KC_END",
      "KC_PGUP",
      "KC_PGDN",
      "RGB_SAD",
      "RGB_SAI",
      "KC_END",
      "KC_NO",
      "CUSTOM(27)",
      "KC_TRNS",
      "KC_TRNS",
      "KC_TRNS",
      "KC_TRNS",
      "KC_TRNS",
      "CUSTOM(25)",
      "RGB_VAI",
      "KC_INS",
      "KC_NO",
      "CUSTOM(7)",
      "KC_NO",
      "KC_RGUI",
      "KC_RALT",
      "KC_NO",
      "RGB_SPD",
      "RGB_VAD",
      "RGB_SPI"
    ]
  ],
  "encoders": [
    [
      ["KC_PGUP", "KC_PGDN"],
      ["KC_VOLD", "KC_VOLU"],
      ["KC_VOLD", "KC_VOLU"],
      ["KC_VOLD", "KC_VOLU"]
    ]
  ]
};

window.DEFAULT_LAYOUT_DATA_2 = {
  "name": "Keychron Q0 Plus",
  "vendorId": "0x3434",
  "productId": "0x0131",
  "matrix": {"rows": 6, "cols": 5},
  "layouts": {
    "keymap":[
      ["0,0\n\n\n\n\n\n\n\n\ne0",{"x":0.25},"0,1","0,2","0,3","0,4"],
      [{"y":0.25},"1,0",{"x":0.25},"1,1","1,2","1,3","1,4"],
      ["2,0",{"x":0.25},"2,1","2,2","2,3",{"h":2},"2,4"],
      ["3,0",{"x":0.25},"3,1","3,2","3,3"],
      ["4,0",{"x":0.25},"4,1","4,2","4,3",{"h":2},"4,4"],
      ["5,0",{"x":0.25,"w":2},"5,1","5,3"]
    ]
  }
};

window.DEFAULT_MAPPING_DATA_2 = {
  "name": "Keychron Q0 Plus",
  "vendorProductId": 875823409,
  "macros": ["{+KC_LCTL}{+KC_LGUI}v{-KC_LGUI}{-KC_LCTL}","","","","","","","","","","","","","","",""],
  "layers": [
    ["KC_ESC","TO(0)","TO(1)","TO(2)","TO(3)","MACRO(1)","KC_ESC","KC_TAB","KC_BSPC","KC_DEL","MACRO(2)","C(KC_7)","C(KC_8)","C(KC_9)","C(KC_G)","KC_F","C(KC_4)","C(KC_5)","C(KC_6)","KC_NO","TT(2)","C(KC_1)","C(KC_2)","C(KC_3)","C(KC_ENT)","MACRO(0)","C(KC_0)","KC_NO","RCS(KC_SPC)","KC_NO"],
    ["KC_TRNS","KC_TRNS","KC_TRNS","KC_TRNS","KC_TRNS","KC_TRNS","KC_NLCK","KC_PSLS","KC_PAST","KC_PMNS","KC_TRNS","KC_P7","KC_P8","KC_P9","KC_PPLS","KC_TRNS","KC_P4","KC_P5","KC_P6","KC_NO","KC_TRNS","KC_P1","KC_P2","KC_P3","KC_PENT","KC_TRNS","KC_P0","KC_NO","KC_PDOT","KC_NO"],
    ["KC_TRNS","KC_TRNS","KC_TRNS","KC_TRNS","KC_TRNS","KC_TRNS","KC_NO","KC_NO","KC_NO","KC_PGUP","KC_TRNS","KC_HOME","KC_UP","KC_END","KC_PGDN","KC_TRNS","KC_LEFT","KC_DOWN","KC_RGHT","KC_NO","KC_TRNS","A(KC_LEFT)","KC_F5","A(KC_RGHT)","KC_ENT","KC_TRNS","KC_NO","KC_NO","KC_NO","KC_NO"],
    ["RGB_TOG","KC_TRNS","KC_TRNS","KC_TRNS","KC_TRNS","RGB_M_P","KC_TRNS","KC_TRNS","KC_TRNS","KC_TRNS","RGB_M_B","KC_TRNS","KC_TRNS","KC_TRNS","KC_TRNS","RGB_M_R","KC_TRNS","KC_TRNS","KC_TRNS","KC_NO","RGB_MOD","KC_TRNS","KC_TRNS","KC_TRNS","KC_TRNS","RGB_RMOD","KC_TRNS","KC_NO","KC_TRNS","KC_NO"]
  ],
  "encoders": [[["KC_PGUP","KC_PGDN"],["KC_TRNS","KC_TRNS"],["KC_TRNS","KC_TRNS"],["RGB_VAD","RGB_VAI"]]]
};
